/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IMyMultiSigAdvancedDeployerInterface extends Interface {
    getFunction(nameOrSignature: "deployMyMultiSigAdvanced" | "deployMyMultiSigAdvancedDeterministic" | "predictMyMultiSigAdvancedAddress"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'deployMyMultiSigAdvanced', values: [string, AddressLike[], BigNumberish, boolean, AddressLike]): string;
encodeFunctionData(functionFragment: 'deployMyMultiSigAdvancedDeterministic', values: [BytesLike, string, AddressLike[], BigNumberish, boolean, AddressLike]): string;
encodeFunctionData(functionFragment: 'predictMyMultiSigAdvancedAddress', values: [BytesLike, string, AddressLike[], BigNumberish, boolean, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'deployMyMultiSigAdvanced', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployMyMultiSigAdvancedDeterministic', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictMyMultiSigAdvancedAddress', data: BytesLike): Result;
  }

  

  export interface IMyMultiSigAdvancedDeployer extends BaseContract {
    
    connect(runner?: ContractRunner | null): IMyMultiSigAdvancedDeployer;
    waitForDeployment(): Promise<this>;

    interface: IMyMultiSigAdvancedDeployerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    deployMyMultiSigAdvanced: TypedContractMethod<
      [contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    deployMyMultiSigAdvancedDeterministic: TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    predictMyMultiSigAdvancedAddress: TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'deployMyMultiSigAdvanced'): TypedContractMethod<
      [contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deployMyMultiSigAdvancedDeterministic'): TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'predictMyMultiSigAdvancedAddress'): TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }