/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IMyMultiSigExtendedDeployerInterface extends Interface {
    getFunction(nameOrSignature: "deployMyMultiSigExtended" | "deployMyMultiSigExtendedDeterministic" | "predictMyMultiSigExtendedAddress"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'deployMyMultiSigExtended', values: [string, AddressLike[], BigNumberish, boolean, AddressLike]): string;
encodeFunctionData(functionFragment: 'deployMyMultiSigExtendedDeterministic', values: [BytesLike, string, AddressLike[], BigNumberish, boolean, AddressLike]): string;
encodeFunctionData(functionFragment: 'predictMyMultiSigExtendedAddress', values: [BytesLike, string, AddressLike[], BigNumberish, boolean, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'deployMyMultiSigExtended', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployMyMultiSigExtendedDeterministic', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictMyMultiSigExtendedAddress', data: BytesLike): Result;
  }

  

  export interface IMyMultiSigExtendedDeployer extends BaseContract {
    
    connect(runner?: ContractRunner | null): IMyMultiSigExtendedDeployer;
    waitForDeployment(): Promise<this>;

    interface: IMyMultiSigExtendedDeployerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    deployMyMultiSigExtended: TypedContractMethod<
      [contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    deployMyMultiSigExtendedDeterministic: TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    predictMyMultiSigExtendedAddress: TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'deployMyMultiSigExtended'): TypedContractMethod<
      [contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deployMyMultiSigExtendedDeterministic'): TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'predictMyMultiSigExtendedAddress'): TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, isOnlyOwnerRequest_: boolean, entryPoint_: AddressLike, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }