/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface MyMultiSigDeployerInterface extends utils.Interface {
  functions: {
    "deployMyMultiSig(string,address[],uint16)": FunctionFragment;
    "deployMyMultiSigDeterministic(bytes32,string,address[],uint16)": FunctionFragment;
    "predictMyMultiSigAddress(bytes32,string,address[],uint16)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "deployMyMultiSig"
      | "deployMyMultiSigDeterministic"
      | "predictMyMultiSigAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployMyMultiSig",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployMyMultiSigDeterministic",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "predictMyMultiSigAddress",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployMyMultiSig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployMyMultiSigDeterministic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictMyMultiSigAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MyMultiSigDeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MyMultiSigDeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployMyMultiSig(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployMyMultiSigDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    predictMyMultiSigAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { contractAddress: string }>;
  };

  deployMyMultiSig(
    contractName_: PromiseOrValue<string>,
    owners_: PromiseOrValue<string>[],
    threshold_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployMyMultiSigDeterministic(
    salt_: PromiseOrValue<BytesLike>,
    contractName_: PromiseOrValue<string>,
    owners_: PromiseOrValue<string>[],
    threshold_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  predictMyMultiSigAddress(
    salt_: PromiseOrValue<BytesLike>,
    contractName_: PromiseOrValue<string>,
    owners_: PromiseOrValue<string>[],
    threshold_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    deployMyMultiSig(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployMyMultiSigDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    predictMyMultiSigAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    deployMyMultiSig(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployMyMultiSigDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    predictMyMultiSigAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployMyMultiSig(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployMyMultiSigDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    predictMyMultiSigAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
