/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MyMultiSigInterface extends Interface {
    getFunction(nameOrSignature: "addOwner" | "approveHash" | "changeThreshold" | "eip712Domain" | "execTransaction(address,uint256,bytes,uint256,uint256,bytes)" | "execTransaction(address,uint256,bytes,uint256,bytes)" | "generateHash" | "getApprovedOwners" | "getMessageHash" | "getOwners" | "getThreshold" | "incrementNonce" | "isMessageSigned" | "isOwner" | "isValidSignature(bytes32,bytes)" | "isValidSignature(address,uint256,bytes,uint256,uint256,uint256,bytes)" | "multiRequest" | "multiRequestStrict" | "name" | "nonce" | "onERC1155BatchReceived" | "onERC1155Received" | "onERC721Received" | "ownerCount" | "removeOwner" | "replaceOwner" | "requireTxSuccess" | "revokeApproval" | "setRequireTxSuccess" | "signMessage" | "supportsInterface" | "threshold" | "unsignMessage" | "version"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApproveHash" | "ContractEndOfLife" | "EIP712DomainChanged" | "MessageSigned" | "MessageUnsigned" | "MultiRequestExecuted" | "OwnerAdded" | "OwnerRemoved" | "RequireTxSuccessSet" | "RevokeApproval" | "ThresholdChanged" | "TransactionExecuted" | "TxFailure"): EventFragment;

    encodeFunctionData(functionFragment: 'addOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'approveHash', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'changeThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'eip712Domain', values?: undefined): string;
encodeFunctionData(functionFragment: 'execTransaction(address,uint256,bytes,uint256,uint256,bytes)', values: [AddressLike, BigNumberish, BytesLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'execTransaction(address,uint256,bytes,uint256,bytes)', values: [AddressLike, BigNumberish, BytesLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'generateHash', values: [AddressLike, BigNumberish, BytesLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getApprovedOwners', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getMessageHash', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getOwners', values?: undefined): string;
encodeFunctionData(functionFragment: 'getThreshold', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'incrementNonce', values?: undefined): string;
encodeFunctionData(functionFragment: 'isMessageSigned', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isValidSignature(bytes32,bytes)', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'isValidSignature(address,uint256,bytes,uint256,uint256,uint256,bytes)', values: [AddressLike, BigNumberish, BytesLike, BigNumberish, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'multiRequest', values: [AddressLike[], BigNumberish[], BytesLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'multiRequestStrict', values: [AddressLike[], BigNumberish[], BytesLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'nonce', values?: undefined): string;
encodeFunctionData(functionFragment: 'onERC1155BatchReceived', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'onERC1155Received', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'onERC721Received', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'ownerCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'replaceOwner', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'requireTxSuccess', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeApproval', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setRequireTxSuccess', values: [boolean]): string;
encodeFunctionData(functionFragment: 'signMessage', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'threshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'unsignMessage', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'changeThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eip712Domain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execTransaction(address,uint256,bytes,uint256,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execTransaction(address,uint256,bytes,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'generateHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApprovedOwners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMessageHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'incrementNonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isMessageSigned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isValidSignature(bytes32,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isValidSignature(address,uint256,bytes,uint256,uint256,uint256,bytes)', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'multiRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'multiRequestStrict', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC1155BatchReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC1155Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'replaceOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requireTxSuccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeApproval', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRequireTxSuccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signMessage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'threshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unsignMessage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
  }

  
    export namespace ApproveHashEvent {
      export type InputTuple = [owner: AddressLike, hash: BytesLike];
      export type OutputTuple = [owner: string, hash: string];
      export interface OutputObject {owner: string, hash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContractEndOfLifeEvent {
      export type InputTuple = [txNonceLefts: BigNumberish];
      export type OutputTuple = [txNonceLefts: bigint];
      export interface OutputObject {txNonceLefts: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EIP712DomainChangedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MessageSignedEvent {
      export type InputTuple = [msgHash: BytesLike];
      export type OutputTuple = [msgHash: string];
      export interface OutputObject {msgHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MessageUnsignedEvent {
      export type InputTuple = [msgHash: BytesLike];
      export type OutputTuple = [msgHash: string];
      export interface OutputObject {msgHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MultiRequestExecutedEvent {
      export type InputTuple = [txNonce: BigNumberish, successes: boolean[], returnData: BytesLike[]];
      export type OutputTuple = [txNonce: bigint, successes: boolean[], returnData: string[]];
      export interface OutputObject {txNonce: bigint, successes: boolean[], returnData: string[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerAddedEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerRemovedEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequireTxSuccessSetEvent {
      export type InputTuple = [required: boolean];
      export type OutputTuple = [required: boolean];
      export interface OutputObject {required: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RevokeApprovalEvent {
      export type InputTuple = [owner: AddressLike, hash: BytesLike];
      export type OutputTuple = [owner: string, hash: string];
      export interface OutputObject {owner: string, hash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ThresholdChangedEvent {
      export type InputTuple = [threshold: BigNumberish];
      export type OutputTuple = [threshold: bigint];
      export interface OutputObject {threshold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransactionExecutedEvent {
      export type InputTuple = [sender: AddressLike, to: AddressLike, value: BigNumberish, data: BytesLike, txnGas: BigNumberish, txnNonce: BigNumberish];
      export type OutputTuple = [sender: string, to: string, value: bigint, data: string, txnGas: bigint, txnNonce: bigint];
      export interface OutputObject {sender: string, to: string, value: bigint, data: string, txnGas: bigint, txnNonce: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TxFailureEvent {
      export type InputTuple = [sender: AddressLike, to: AddressLike, value: BigNumberish, data: BytesLike, txnGas: BigNumberish, txnNonce: BigNumberish, reason: BytesLike];
      export type OutputTuple = [sender: string, to: string, value: bigint, data: string, txnGas: bigint, txnNonce: bigint, reason: string];
      export interface OutputObject {sender: string, to: string, value: bigint, data: string, txnGas: bigint, txnNonce: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MyMultiSig extends BaseContract {
    
    connect(runner?: ContractRunner | null): MyMultiSig;
    waitForDeployment(): Promise<this>;

    interface: MyMultiSigInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addOwner: TypedContractMethod<
      [owner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    approveHash: TypedContractMethod<
      [hash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    changeThreshold: TypedContractMethod<
      [newThreshold: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    eip712Domain: TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >
    

    
    "execTransaction(address,uint256,bytes,uint256,uint256,bytes)": TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, txnGas: BigNumberish, validUntil: BigNumberish, signatures: BytesLike, ],
      [boolean],
      'payable'
    >
    

    
    "execTransaction(address,uint256,bytes,uint256,bytes)": TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, txnGas: BigNumberish, signatures: BytesLike, ],
      [boolean],
      'payable'
    >
    

    
    generateHash: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, txnGas: BigNumberish, txnNonce: BigNumberish, validUntil: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getApprovedOwners: TypedContractMethod<
      [hash: BytesLike, ],
      [string[]],
      'view'
    >
    

    
    getMessageHash: TypedContractMethod<
      [message: BytesLike, ],
      [string],
      'view'
    >
    

    
    getOwners: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getThreshold: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    incrementNonce: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    isMessageSigned: TypedContractMethod<
      [msgHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    isOwner: TypedContractMethod<
      [owner: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    "isValidSignature(bytes32,bytes)": TypedContractMethod<
      [hash: BytesLike, signature: BytesLike, ],
      [string],
      'view'
    >
    

    
    "isValidSignature(address,uint256,bytes,uint256,uint256,uint256,bytes)": TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, txnGas: BigNumberish, txnNonce: BigNumberish, validUntil: BigNumberish, signatures: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    multiRequest: TypedContractMethod<
      [to: AddressLike[], value: BigNumberish[], data: BytesLike[], txGas: BigNumberish[], ],
      [[boolean[], string[]] & {successes: boolean[], returnData: string[] }],
      'payable'
    >
    

    
    multiRequestStrict: TypedContractMethod<
      [to: AddressLike[], value: BigNumberish[], data: BytesLike[], txGas: BigNumberish[], ],
      [void],
      'payable'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    nonce: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    onERC1155BatchReceived: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish[], arg3: BigNumberish[], arg4: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    onERC1155Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    onERC721Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    ownerCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    removeOwner: TypedContractMethod<
      [owner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    replaceOwner: TypedContractMethod<
      [oldOwner: AddressLike, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    requireTxSuccess: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    revokeApproval: TypedContractMethod<
      [hash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setRequireTxSuccess: TypedContractMethod<
      [required: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    signMessage: TypedContractMethod<
      [message: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    threshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unsignMessage: TypedContractMethod<
      [message: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    version: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addOwner'): TypedContractMethod<
      [owner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveHash'): TypedContractMethod<
      [hash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'changeThreshold'): TypedContractMethod<
      [newThreshold: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'eip712Domain'): TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'execTransaction(address,uint256,bytes,uint256,uint256,bytes)'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, txnGas: BigNumberish, validUntil: BigNumberish, signatures: BytesLike, ],
      [boolean],
      'payable'
    >;
getFunction(nameOrSignature: 'execTransaction(address,uint256,bytes,uint256,bytes)'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, txnGas: BigNumberish, signatures: BytesLike, ],
      [boolean],
      'payable'
    >;
getFunction(nameOrSignature: 'generateHash'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, txnGas: BigNumberish, txnNonce: BigNumberish, validUntil: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getApprovedOwners'): TypedContractMethod<
      [hash: BytesLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getMessageHash'): TypedContractMethod<
      [message: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOwners'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getThreshold'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'incrementNonce'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isMessageSigned'): TypedContractMethod<
      [msgHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isOwner'): TypedContractMethod<
      [owner: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isValidSignature(bytes32,bytes)'): TypedContractMethod<
      [hash: BytesLike, signature: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isValidSignature(address,uint256,bytes,uint256,uint256,uint256,bytes)'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, data: BytesLike, txnGas: BigNumberish, txnNonce: BigNumberish, validUntil: BigNumberish, signatures: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'multiRequest'): TypedContractMethod<
      [to: AddressLike[], value: BigNumberish[], data: BytesLike[], txGas: BigNumberish[], ],
      [[boolean[], string[]] & {successes: boolean[], returnData: string[] }],
      'payable'
    >;
getFunction(nameOrSignature: 'multiRequestStrict'): TypedContractMethod<
      [to: AddressLike[], value: BigNumberish[], data: BytesLike[], txGas: BigNumberish[], ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nonce'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'onERC1155BatchReceived'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish[], arg3: BigNumberish[], arg4: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onERC1155Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onERC721Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ownerCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'removeOwner'): TypedContractMethod<
      [owner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'replaceOwner'): TypedContractMethod<
      [oldOwner: AddressLike, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requireTxSuccess'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'revokeApproval'): TypedContractMethod<
      [hash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRequireTxSuccess'): TypedContractMethod<
      [required: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'signMessage'): TypedContractMethod<
      [message: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'threshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unsignMessage'): TypedContractMethod<
      [message: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ApproveHash'): TypedContractEvent<ApproveHashEvent.InputTuple, ApproveHashEvent.OutputTuple, ApproveHashEvent.OutputObject>;
getEvent(key: 'ContractEndOfLife'): TypedContractEvent<ContractEndOfLifeEvent.InputTuple, ContractEndOfLifeEvent.OutputTuple, ContractEndOfLifeEvent.OutputObject>;
getEvent(key: 'EIP712DomainChanged'): TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
getEvent(key: 'MessageSigned'): TypedContractEvent<MessageSignedEvent.InputTuple, MessageSignedEvent.OutputTuple, MessageSignedEvent.OutputObject>;
getEvent(key: 'MessageUnsigned'): TypedContractEvent<MessageUnsignedEvent.InputTuple, MessageUnsignedEvent.OutputTuple, MessageUnsignedEvent.OutputObject>;
getEvent(key: 'MultiRequestExecuted'): TypedContractEvent<MultiRequestExecutedEvent.InputTuple, MultiRequestExecutedEvent.OutputTuple, MultiRequestExecutedEvent.OutputObject>;
getEvent(key: 'OwnerAdded'): TypedContractEvent<OwnerAddedEvent.InputTuple, OwnerAddedEvent.OutputTuple, OwnerAddedEvent.OutputObject>;
getEvent(key: 'OwnerRemoved'): TypedContractEvent<OwnerRemovedEvent.InputTuple, OwnerRemovedEvent.OutputTuple, OwnerRemovedEvent.OutputObject>;
getEvent(key: 'RequireTxSuccessSet'): TypedContractEvent<RequireTxSuccessSetEvent.InputTuple, RequireTxSuccessSetEvent.OutputTuple, RequireTxSuccessSetEvent.OutputObject>;
getEvent(key: 'RevokeApproval'): TypedContractEvent<RevokeApprovalEvent.InputTuple, RevokeApprovalEvent.OutputTuple, RevokeApprovalEvent.OutputObject>;
getEvent(key: 'ThresholdChanged'): TypedContractEvent<ThresholdChangedEvent.InputTuple, ThresholdChangedEvent.OutputTuple, ThresholdChangedEvent.OutputObject>;
getEvent(key: 'TransactionExecuted'): TypedContractEvent<TransactionExecutedEvent.InputTuple, TransactionExecutedEvent.OutputTuple, TransactionExecutedEvent.OutputObject>;
getEvent(key: 'TxFailure'): TypedContractEvent<TxFailureEvent.InputTuple, TxFailureEvent.OutputTuple, TxFailureEvent.OutputObject>;

    filters: {
      
      'ApproveHash(address,bytes32)': TypedContractEvent<ApproveHashEvent.InputTuple, ApproveHashEvent.OutputTuple, ApproveHashEvent.OutputObject>;
      ApproveHash: TypedContractEvent<ApproveHashEvent.InputTuple, ApproveHashEvent.OutputTuple, ApproveHashEvent.OutputObject>;
    

      'ContractEndOfLife(uint256)': TypedContractEvent<ContractEndOfLifeEvent.InputTuple, ContractEndOfLifeEvent.OutputTuple, ContractEndOfLifeEvent.OutputObject>;
      ContractEndOfLife: TypedContractEvent<ContractEndOfLifeEvent.InputTuple, ContractEndOfLifeEvent.OutputTuple, ContractEndOfLifeEvent.OutputObject>;
    

      'EIP712DomainChanged()': TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
      EIP712DomainChanged: TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
    

      'MessageSigned(bytes32)': TypedContractEvent<MessageSignedEvent.InputTuple, MessageSignedEvent.OutputTuple, MessageSignedEvent.OutputObject>;
      MessageSigned: TypedContractEvent<MessageSignedEvent.InputTuple, MessageSignedEvent.OutputTuple, MessageSignedEvent.OutputObject>;
    

      'MessageUnsigned(bytes32)': TypedContractEvent<MessageUnsignedEvent.InputTuple, MessageUnsignedEvent.OutputTuple, MessageUnsignedEvent.OutputObject>;
      MessageUnsigned: TypedContractEvent<MessageUnsignedEvent.InputTuple, MessageUnsignedEvent.OutputTuple, MessageUnsignedEvent.OutputObject>;
    

      'MultiRequestExecuted(uint256,bool[],bytes[])': TypedContractEvent<MultiRequestExecutedEvent.InputTuple, MultiRequestExecutedEvent.OutputTuple, MultiRequestExecutedEvent.OutputObject>;
      MultiRequestExecuted: TypedContractEvent<MultiRequestExecutedEvent.InputTuple, MultiRequestExecutedEvent.OutputTuple, MultiRequestExecutedEvent.OutputObject>;
    

      'OwnerAdded(address)': TypedContractEvent<OwnerAddedEvent.InputTuple, OwnerAddedEvent.OutputTuple, OwnerAddedEvent.OutputObject>;
      OwnerAdded: TypedContractEvent<OwnerAddedEvent.InputTuple, OwnerAddedEvent.OutputTuple, OwnerAddedEvent.OutputObject>;
    

      'OwnerRemoved(address)': TypedContractEvent<OwnerRemovedEvent.InputTuple, OwnerRemovedEvent.OutputTuple, OwnerRemovedEvent.OutputObject>;
      OwnerRemoved: TypedContractEvent<OwnerRemovedEvent.InputTuple, OwnerRemovedEvent.OutputTuple, OwnerRemovedEvent.OutputObject>;
    

      'RequireTxSuccessSet(bool)': TypedContractEvent<RequireTxSuccessSetEvent.InputTuple, RequireTxSuccessSetEvent.OutputTuple, RequireTxSuccessSetEvent.OutputObject>;
      RequireTxSuccessSet: TypedContractEvent<RequireTxSuccessSetEvent.InputTuple, RequireTxSuccessSetEvent.OutputTuple, RequireTxSuccessSetEvent.OutputObject>;
    

      'RevokeApproval(address,bytes32)': TypedContractEvent<RevokeApprovalEvent.InputTuple, RevokeApprovalEvent.OutputTuple, RevokeApprovalEvent.OutputObject>;
      RevokeApproval: TypedContractEvent<RevokeApprovalEvent.InputTuple, RevokeApprovalEvent.OutputTuple, RevokeApprovalEvent.OutputObject>;
    

      'ThresholdChanged(uint256)': TypedContractEvent<ThresholdChangedEvent.InputTuple, ThresholdChangedEvent.OutputTuple, ThresholdChangedEvent.OutputObject>;
      ThresholdChanged: TypedContractEvent<ThresholdChangedEvent.InputTuple, ThresholdChangedEvent.OutputTuple, ThresholdChangedEvent.OutputObject>;
    

      'TransactionExecuted(address,address,uint256,bytes,uint256,uint256)': TypedContractEvent<TransactionExecutedEvent.InputTuple, TransactionExecutedEvent.OutputTuple, TransactionExecutedEvent.OutputObject>;
      TransactionExecuted: TypedContractEvent<TransactionExecutedEvent.InputTuple, TransactionExecutedEvent.OutputTuple, TransactionExecutedEvent.OutputObject>;
    

      'TxFailure(address,address,uint256,bytes,uint256,uint256,bytes)': TypedContractEvent<TxFailureEvent.InputTuple, TxFailureEvent.OutputTuple, TxFailureEvent.OutputObject>;
      TxFailure: TypedContractEvent<TxFailureEvent.InputTuple, TxFailureEvent.OutputTuple, TxFailureEvent.OutputObject>;
    
    };
  }