/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace MyMultiSigV2_5FactorableModels {
  export type Create2ParamsStruct = {
    saltKind: PromiseOrValue<BigNumberish>;
    chainAgnosticKey: PromiseOrValue<BytesLike>;
    contractName: PromiseOrValue<string>;
    owners: PromiseOrValue<string>[];
    threshold: PromiseOrValue<BigNumberish>;
  };

  export type Create2ParamsStructOutput = [
    number,
    string,
    string,
    string[],
    number
  ] & {
    saltKind: number;
    chainAgnosticKey: string;
    contractName: string;
    owners: string[];
    threshold: number;
  };
}

export interface MyMultiSigFactoryInterface extends utils.Interface {
  functions: {
    "advancedCount()": FunctionFragment;
    "computeSalt((uint8,bytes32,string,address[],uint16))": FunctionFragment;
    "createMultiSig(string,address[],uint16)": FunctionFragment;
    "createMyMultiSigAdvanced(string,address[],uint16,bool)": FunctionFragment;
    "createMyMultiSigExtended(string,address[],uint16,bool)": FunctionFragment;
    "createMyMultiSigV2_5((uint8,bytes32,string,address[],uint16),address)": FunctionFragment;
    "creationType(uint256)": FunctionFragment;
    "creationTypeCount(uint8)": FunctionFragment;
    "creationTypeOf(address)": FunctionFragment;
    "extendedCount()": FunctionFragment;
    "initialize()": FunctionFragment;
    "isAdvanced(uint256)": FunctionFragment;
    "isExtended(address)": FunctionFragment;
    "isV2_5Wallet(address)": FunctionFragment;
    "multiSig(uint256)": FunctionFragment;
    "multiSigByCreator(address,uint256)": FunctionFragment;
    "multiSigCount()": FunctionFragment;
    "multiSigCreatorCount(address)": FunctionFragment;
    "myMultiSigAdvancedDeployer()": FunctionFragment;
    "myMultiSigDeployer()": FunctionFragment;
    "myMultiSigExtendedDeployer()": FunctionFragment;
    "myMultiSigV2_5Deployer()": FunctionFragment;
    "myMultiSigV2_5Impl()": FunctionFragment;
    "name()": FunctionFragment;
    "predictWalletAddress((uint8,bytes32,string,address[],uint16))": FunctionFragment;
    "reinitializeV2_5()": FunctionFragment;
    "simpleCount()": FunctionFragment;
    "v2_5Count()": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "advancedCount"
      | "computeSalt"
      | "createMultiSig"
      | "createMyMultiSigAdvanced"
      | "createMyMultiSigExtended"
      | "createMyMultiSigV2_5"
      | "creationType"
      | "creationTypeCount"
      | "creationTypeOf"
      | "extendedCount"
      | "initialize"
      | "isAdvanced"
      | "isExtended"
      | "isV2_5Wallet"
      | "multiSig"
      | "multiSigByCreator"
      | "multiSigCount"
      | "multiSigCreatorCount"
      | "myMultiSigAdvancedDeployer"
      | "myMultiSigDeployer"
      | "myMultiSigExtendedDeployer"
      | "myMultiSigV2_5Deployer"
      | "myMultiSigV2_5Impl"
      | "name"
      | "predictWalletAddress"
      | "reinitializeV2_5"
      | "simpleCount"
      | "v2_5Count"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "advancedCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "computeSalt",
    values: [MyMultiSigV2_5FactorableModels.Create2ParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createMultiSig",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createMyMultiSigAdvanced",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createMyMultiSigExtended",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createMyMultiSigV2_5",
    values: [
      MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "creationType",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "creationTypeCount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "creationTypeOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "extendedCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAdvanced",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isExtended",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isV2_5Wallet",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "multiSig",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "multiSigByCreator",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "multiSigCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "multiSigCreatorCount",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "myMultiSigAdvancedDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "myMultiSigDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "myMultiSigExtendedDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "myMultiSigV2_5Deployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "myMultiSigV2_5Impl",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predictWalletAddress",
    values: [MyMultiSigV2_5FactorableModels.Create2ParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "reinitializeV2_5",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "simpleCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "v2_5Count", values?: undefined): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "advancedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeSalt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMultiSig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMyMultiSigAdvanced",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMyMultiSigExtended",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMyMultiSigV2_5",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creationType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creationTypeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creationTypeOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdvanced", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExtended", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isV2_5Wallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multiSig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multiSigByCreator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiSigCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "multiSigCreatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "myMultiSigAdvancedDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "myMultiSigDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "myMultiSigExtendedDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "myMultiSigV2_5Deployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "myMultiSigV2_5Impl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictWalletAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reinitializeV2_5",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simpleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "v2_5Count", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "MyMultiSigCreated(address,address,uint256,string,address[],uint16)": EventFragment;
    "MyMultiSigV2_5Created(address,address,bytes32,string,address[],uint16)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MyMultiSigCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MyMultiSigV2_5Created"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface MyMultiSigCreatedEventObject {
  creator: string;
  contractAddress: string;
  contractIndex: BigNumber;
  contractName: string;
  originalOwners: string[];
  threshold: number;
}
export type MyMultiSigCreatedEvent = TypedEvent<
  [string, string, BigNumber, string, string[], number],
  MyMultiSigCreatedEventObject
>;

export type MyMultiSigCreatedEventFilter =
  TypedEventFilter<MyMultiSigCreatedEvent>;

export interface MyMultiSigV2_5CreatedEventObject {
  creator: string;
  contractAddress: string;
  salt: string;
  contractName: string;
  originalOwners: string[];
  threshold: number;
}
export type MyMultiSigV2_5CreatedEvent = TypedEvent<
  [string, string, string, string, string[], number],
  MyMultiSigV2_5CreatedEventObject
>;

export type MyMultiSigV2_5CreatedEventFilter =
  TypedEventFilter<MyMultiSigV2_5CreatedEvent>;

export interface MyMultiSigFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MyMultiSigFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    advancedCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    computeSalt(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    createMultiSig(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createMyMultiSigAdvanced(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createMyMultiSigExtended(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createMyMultiSigV2_5(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      entryPoint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    creationType(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    creationTypeCount(
      kind: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    creationTypeOf(
      contractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    extendedCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isAdvanced(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isExtended(
      contractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isV2_5Wallet(
      wallet: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    multiSig(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    multiSigByCreator(
      creator: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    multiSigCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    multiSigCreatorCount(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    myMultiSigAdvancedDeployer(overrides?: CallOverrides): Promise<[string]>;

    myMultiSigDeployer(overrides?: CallOverrides): Promise<[string]>;

    myMultiSigExtendedDeployer(overrides?: CallOverrides): Promise<[string]>;

    myMultiSigV2_5Deployer(overrides?: CallOverrides): Promise<[string]>;

    myMultiSigV2_5Impl(overrides?: CallOverrides): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    predictWalletAddress(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<[string, string] & { wallet: string; impl: string }>;

    reinitializeV2_5(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    simpleCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    v2_5Count(overrides?: CallOverrides): Promise<[BigNumber]>;

    version(overrides?: CallOverrides): Promise<[string]>;
  };

  advancedCount(overrides?: CallOverrides): Promise<BigNumber>;

  computeSalt(
    params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  createMultiSig(
    contractName: PromiseOrValue<string>,
    owners: PromiseOrValue<string>[],
    threshold: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createMyMultiSigAdvanced(
    contractName: PromiseOrValue<string>,
    owners: PromiseOrValue<string>[],
    threshold: PromiseOrValue<BigNumberish>,
    isOnlyOwnerRequest: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createMyMultiSigExtended(
    contractName: PromiseOrValue<string>,
    owners: PromiseOrValue<string>[],
    threshold: PromiseOrValue<BigNumberish>,
    isOnlyOwnerRequest: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createMyMultiSigV2_5(
    params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
    entryPoint: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  creationType(
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  creationTypeCount(
    kind: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  creationTypeOf(
    contractAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<number>;

  extendedCount(overrides?: CallOverrides): Promise<BigNumber>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isAdvanced(
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isExtended(
    contractAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isV2_5Wallet(
    wallet: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  multiSig(
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  multiSigByCreator(
    creator: PromiseOrValue<string>,
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  multiSigCount(overrides?: CallOverrides): Promise<BigNumber>;

  multiSigCreatorCount(
    creator: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  myMultiSigAdvancedDeployer(overrides?: CallOverrides): Promise<string>;

  myMultiSigDeployer(overrides?: CallOverrides): Promise<string>;

  myMultiSigExtendedDeployer(overrides?: CallOverrides): Promise<string>;

  myMultiSigV2_5Deployer(overrides?: CallOverrides): Promise<string>;

  myMultiSigV2_5Impl(overrides?: CallOverrides): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  predictWalletAddress(
    params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
    overrides?: CallOverrides
  ): Promise<[string, string] & { wallet: string; impl: string }>;

  reinitializeV2_5(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  simpleCount(overrides?: CallOverrides): Promise<BigNumber>;

  v2_5Count(overrides?: CallOverrides): Promise<BigNumber>;

  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    advancedCount(overrides?: CallOverrides): Promise<BigNumber>;

    computeSalt(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    createMultiSig(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    createMyMultiSigAdvanced(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string>;

    createMyMultiSigExtended(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string>;

    createMyMultiSigV2_5(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      entryPoint: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    creationType(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    creationTypeCount(
      kind: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    creationTypeOf(
      contractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<number>;

    extendedCount(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(overrides?: CallOverrides): Promise<void>;

    isAdvanced(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isExtended(
      contractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isV2_5Wallet(
      wallet: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    multiSig(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    multiSigByCreator(
      creator: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    multiSigCount(overrides?: CallOverrides): Promise<BigNumber>;

    multiSigCreatorCount(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    myMultiSigAdvancedDeployer(overrides?: CallOverrides): Promise<string>;

    myMultiSigDeployer(overrides?: CallOverrides): Promise<string>;

    myMultiSigExtendedDeployer(overrides?: CallOverrides): Promise<string>;

    myMultiSigV2_5Deployer(overrides?: CallOverrides): Promise<string>;

    myMultiSigV2_5Impl(overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    predictWalletAddress(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<[string, string] & { wallet: string; impl: string }>;

    reinitializeV2_5(overrides?: CallOverrides): Promise<void>;

    simpleCount(overrides?: CallOverrides): Promise<BigNumber>;

    v2_5Count(overrides?: CallOverrides): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "MyMultiSigCreated(address,address,uint256,string,address[],uint16)"(
      creator?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      contractIndex?: PromiseOrValue<BigNumberish> | null,
      contractName?: null,
      originalOwners?: null,
      threshold?: null
    ): MyMultiSigCreatedEventFilter;
    MyMultiSigCreated(
      creator?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      contractIndex?: PromiseOrValue<BigNumberish> | null,
      contractName?: null,
      originalOwners?: null,
      threshold?: null
    ): MyMultiSigCreatedEventFilter;

    "MyMultiSigV2_5Created(address,address,bytes32,string,address[],uint16)"(
      creator?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      salt?: null,
      contractName?: null,
      originalOwners?: null,
      threshold?: null
    ): MyMultiSigV2_5CreatedEventFilter;
    MyMultiSigV2_5Created(
      creator?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      salt?: null,
      contractName?: null,
      originalOwners?: null,
      threshold?: null
    ): MyMultiSigV2_5CreatedEventFilter;
  };

  estimateGas: {
    advancedCount(overrides?: CallOverrides): Promise<BigNumber>;

    computeSalt(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createMultiSig(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createMyMultiSigAdvanced(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createMyMultiSigExtended(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createMyMultiSigV2_5(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      entryPoint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    creationType(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    creationTypeCount(
      kind: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    creationTypeOf(
      contractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    extendedCount(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isAdvanced(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isExtended(
      contractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isV2_5Wallet(
      wallet: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    multiSig(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    multiSigByCreator(
      creator: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    multiSigCount(overrides?: CallOverrides): Promise<BigNumber>;

    multiSigCreatorCount(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    myMultiSigAdvancedDeployer(overrides?: CallOverrides): Promise<BigNumber>;

    myMultiSigDeployer(overrides?: CallOverrides): Promise<BigNumber>;

    myMultiSigExtendedDeployer(overrides?: CallOverrides): Promise<BigNumber>;

    myMultiSigV2_5Deployer(overrides?: CallOverrides): Promise<BigNumber>;

    myMultiSigV2_5Impl(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    predictWalletAddress(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reinitializeV2_5(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    simpleCount(overrides?: CallOverrides): Promise<BigNumber>;

    v2_5Count(overrides?: CallOverrides): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    advancedCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    computeSalt(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createMultiSig(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createMyMultiSigAdvanced(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createMyMultiSigExtended(
      contractName: PromiseOrValue<string>,
      owners: PromiseOrValue<string>[],
      threshold: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createMyMultiSigV2_5(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      entryPoint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    creationType(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    creationTypeCount(
      kind: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    creationTypeOf(
      contractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    extendedCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isAdvanced(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isExtended(
      contractAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isV2_5Wallet(
      wallet: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multiSig(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multiSigByCreator(
      creator: PromiseOrValue<string>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    multiSigCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    multiSigCreatorCount(
      creator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    myMultiSigAdvancedDeployer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    myMultiSigDeployer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    myMultiSigExtendedDeployer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    myMultiSigV2_5Deployer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    myMultiSigV2_5Impl(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    predictWalletAddress(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reinitializeV2_5(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    simpleCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    v2_5Count(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
