/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MyMultiSigFactoryInterface extends Interface {
    getFunction(nameOrSignature: "advancedCount" | "computeSalt" | "createDeterministicMultiSig" | "createDeterministicMyMultiSigAdvanced" | "createDeterministicMyMultiSigExtended" | "createMultiSig" | "createMyMultiSigAdvanced" | "createMyMultiSigExtended" | "creationType" | "creationTypeCount" | "creationTypeOf" | "extendedCount" | "initialize" | "isAdvanced" | "isExtended" | "multiSig" | "multiSigByCreator" | "multiSigCount" | "multiSigCreatorCount" | "myMultiSigAdvancedDeployer" | "myMultiSigDeployer" | "myMultiSigExtendedDeployer" | "name" | "predictMultiSigAddress" | "predictMyMultiSigAdvancedAddress" | "predictMyMultiSigExtendedAddress" | "simpleCount" | "version"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Initialized" | "MyMultiSigCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'advancedCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'computeSalt', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'createDeterministicMultiSig', values: [string, AddressLike[], BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'createDeterministicMyMultiSigAdvanced', values: [string, AddressLike[], BigNumberish, boolean, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'createDeterministicMyMultiSigExtended', values: [string, AddressLike[], BigNumberish, boolean, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'createMultiSig', values: [string, AddressLike[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'createMyMultiSigAdvanced', values: [string, AddressLike[], BigNumberish, boolean, AddressLike]): string;
encodeFunctionData(functionFragment: 'createMyMultiSigExtended', values: [string, AddressLike[], BigNumberish, boolean, AddressLike]): string;
encodeFunctionData(functionFragment: 'creationType', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'creationTypeCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'creationTypeOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'extendedCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values?: undefined): string;
encodeFunctionData(functionFragment: 'isAdvanced', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isExtended', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'multiSig', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'multiSigByCreator', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'multiSigCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'multiSigCreatorCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'myMultiSigAdvancedDeployer', values?: undefined): string;
encodeFunctionData(functionFragment: 'myMultiSigDeployer', values?: undefined): string;
encodeFunctionData(functionFragment: 'myMultiSigExtendedDeployer', values?: undefined): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'predictMultiSigAddress', values: [AddressLike, string, AddressLike[], BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'predictMyMultiSigAdvancedAddress', values: [AddressLike, string, AddressLike[], BigNumberish, boolean, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'predictMyMultiSigExtendedAddress', values: [AddressLike, string, AddressLike[], BigNumberish, boolean, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'simpleCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'advancedCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'computeSalt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createDeterministicMultiSig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createDeterministicMyMultiSigAdvanced', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createDeterministicMyMultiSigExtended', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMultiSig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMyMultiSigAdvanced', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMyMultiSigExtended', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creationType', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creationTypeCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creationTypeOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'extendedCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAdvanced', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isExtended', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'multiSig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'multiSigByCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'multiSigCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'multiSigCreatorCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'myMultiSigAdvancedDeployer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'myMultiSigDeployer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'myMultiSigExtendedDeployer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictMultiSigAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictMyMultiSigAdvancedAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictMyMultiSigExtendedAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'simpleCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
  }

  
    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MyMultiSigCreatedEvent {
      export type InputTuple = [creator: AddressLike, contractAddress: AddressLike, contractIndex: BigNumberish, contractName: string, originalOwners: AddressLike[], threshold: BigNumberish];
      export type OutputTuple = [creator: string, contractAddress: string, contractIndex: bigint, contractName: string, originalOwners: string[], threshold: bigint];
      export interface OutputObject {creator: string, contractAddress: string, contractIndex: bigint, contractName: string, originalOwners: string[], threshold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MyMultiSigFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): MyMultiSigFactory;
    waitForDeployment(): Promise<this>;

    interface: MyMultiSigFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    advancedCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    computeSalt: TypedContractMethod<
      [creator: AddressLike, salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    createDeterministicMultiSig: TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, salt: BytesLike, ],
      [string],
      'payable'
    >
    

    
    createDeterministicMyMultiSigAdvanced: TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, salt: BytesLike, ],
      [string],
      'payable'
    >
    

    
    createDeterministicMyMultiSigExtended: TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, salt: BytesLike, ],
      [string],
      'payable'
    >
    

    
    createMultiSig: TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, ],
      [string],
      'payable'
    >
    

    
    createMyMultiSigAdvanced: TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, ],
      [string],
      'payable'
    >
    

    
    createMyMultiSigExtended: TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, ],
      [string],
      'payable'
    >
    

    
    creationType: TypedContractMethod<
      [index: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    creationTypeCount: TypedContractMethod<
      [kind: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    creationTypeOf: TypedContractMethod<
      [contractAddress: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    extendedCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    isAdvanced: TypedContractMethod<
      [index: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isExtended: TypedContractMethod<
      [contractAddress: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    multiSig: TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    multiSigByCreator: TypedContractMethod<
      [creator: AddressLike, index: BigNumberish, ],
      [string],
      'view'
    >
    

    
    multiSigCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    multiSigCreatorCount: TypedContractMethod<
      [creator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    myMultiSigAdvancedDeployer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    myMultiSigDeployer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    myMultiSigExtendedDeployer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    predictMultiSigAddress: TypedContractMethod<
      [creator: AddressLike, contractName: string, owners: AddressLike[], threshold: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    predictMyMultiSigAdvancedAddress: TypedContractMethod<
      [creator: AddressLike, contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    predictMyMultiSigExtendedAddress: TypedContractMethod<
      [creator: AddressLike, contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, salt: BytesLike, ],
      [string],
      'view'
    >
    

    
    simpleCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    version: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'advancedCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'computeSalt'): TypedContractMethod<
      [creator: AddressLike, salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createDeterministicMultiSig'): TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, salt: BytesLike, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'createDeterministicMyMultiSigAdvanced'): TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, salt: BytesLike, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'createDeterministicMyMultiSigExtended'): TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, salt: BytesLike, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'createMultiSig'): TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'createMyMultiSigAdvanced'): TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'createMyMultiSigExtended'): TypedContractMethod<
      [contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'creationType'): TypedContractMethod<
      [index: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'creationTypeCount'): TypedContractMethod<
      [kind: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'creationTypeOf'): TypedContractMethod<
      [contractAddress: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'extendedCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isAdvanced'): TypedContractMethod<
      [index: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isExtended'): TypedContractMethod<
      [contractAddress: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'multiSig'): TypedContractMethod<
      [index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'multiSigByCreator'): TypedContractMethod<
      [creator: AddressLike, index: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'multiSigCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'multiSigCreatorCount'): TypedContractMethod<
      [creator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'myMultiSigAdvancedDeployer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'myMultiSigDeployer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'myMultiSigExtendedDeployer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'predictMultiSigAddress'): TypedContractMethod<
      [creator: AddressLike, contractName: string, owners: AddressLike[], threshold: BigNumberish, salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'predictMyMultiSigAdvancedAddress'): TypedContractMethod<
      [creator: AddressLike, contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'predictMyMultiSigExtendedAddress'): TypedContractMethod<
      [creator: AddressLike, contractName: string, owners: AddressLike[], threshold: BigNumberish, isOnlyOwnerRequest: boolean, entryPoint: AddressLike, salt: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'simpleCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'MyMultiSigCreated'): TypedContractEvent<MyMultiSigCreatedEvent.InputTuple, MyMultiSigCreatedEvent.OutputTuple, MyMultiSigCreatedEvent.OutputObject>;

    filters: {
      
      'Initialized(uint8)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'MyMultiSigCreated(address,address,uint256,string,address[],uint16)': TypedContractEvent<MyMultiSigCreatedEvent.InputTuple, MyMultiSigCreatedEvent.OutputTuple, MyMultiSigCreatedEvent.OutputObject>;
      MyMultiSigCreated: TypedContractEvent<MyMultiSigCreatedEvent.InputTuple, MyMultiSigCreatedEvent.OutputTuple, MyMultiSigCreatedEvent.OutputObject>;
    
    };
  }