/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface MyMultiSigAdvancedDeployerInterface extends utils.Interface {
  functions: {
    "deployMyMultiSigAdvanced(string,address[],uint16,bool,address)": FunctionFragment;
    "deployMyMultiSigAdvancedDeterministic(bytes32,string,address[],uint16,bool,address)": FunctionFragment;
    "extendedDeployer()": FunctionFragment;
    "predictMyMultiSigAdvancedAddress(bytes32,string,address[],uint16,bool,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "deployMyMultiSigAdvanced"
      | "deployMyMultiSigAdvancedDeterministic"
      | "extendedDeployer"
      | "predictMyMultiSigAdvancedAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployMyMultiSigAdvanced",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployMyMultiSigAdvancedDeterministic",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "extendedDeployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "predictMyMultiSigAdvancedAddress",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "deployMyMultiSigAdvanced",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployMyMultiSigAdvancedDeterministic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendedDeployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictMyMultiSigAdvancedAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MyMultiSigAdvancedDeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MyMultiSigAdvancedDeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployMyMultiSigAdvanced(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployMyMultiSigAdvancedDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    extendedDeployer(overrides?: CallOverrides): Promise<[string]>;

    predictMyMultiSigAdvancedAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string] & { contractAddress: string }>;
  };

  deployMyMultiSigAdvanced(
    contractName_: PromiseOrValue<string>,
    owners_: PromiseOrValue<string>[],
    threshold_: PromiseOrValue<BigNumberish>,
    isOnlyOwnerRequest_: PromiseOrValue<boolean>,
    entryPoint_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployMyMultiSigAdvancedDeterministic(
    salt_: PromiseOrValue<BytesLike>,
    contractName_: PromiseOrValue<string>,
    owners_: PromiseOrValue<string>[],
    threshold_: PromiseOrValue<BigNumberish>,
    isOnlyOwnerRequest_: PromiseOrValue<boolean>,
    entryPoint_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  extendedDeployer(overrides?: CallOverrides): Promise<string>;

  predictMyMultiSigAdvancedAddress(
    salt_: PromiseOrValue<BytesLike>,
    contractName_: PromiseOrValue<string>,
    owners_: PromiseOrValue<string>[],
    threshold_: PromiseOrValue<BigNumberish>,
    isOnlyOwnerRequest_: PromiseOrValue<boolean>,
    entryPoint_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    deployMyMultiSigAdvanced(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployMyMultiSigAdvancedDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    extendedDeployer(overrides?: CallOverrides): Promise<string>;

    predictMyMultiSigAdvancedAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    deployMyMultiSigAdvanced(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployMyMultiSigAdvancedDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    extendedDeployer(overrides?: CallOverrides): Promise<BigNumber>;

    predictMyMultiSigAdvancedAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deployMyMultiSigAdvanced(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployMyMultiSigAdvancedDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    extendedDeployer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    predictMyMultiSigAdvancedAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
