/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface MyMultiSigExtendedDeployerInterface extends utils.Interface {
  functions: {
    "creationCodeStores()": FunctionFragment;
    "deployMyMultiSigExtended(string,address[],uint16,bool,address)": FunctionFragment;
    "deployMyMultiSigExtendedDeterministic(bytes32,string,address[],uint16,bool,address)": FunctionFragment;
    "predictMyMultiSigExtendedAddress(bytes32,string,address[],uint16,bool,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "creationCodeStores"
      | "deployMyMultiSigExtended"
      | "deployMyMultiSigExtendedDeterministic"
      | "predictMyMultiSigExtendedAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "creationCodeStores",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployMyMultiSigExtended",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployMyMultiSigExtendedDeterministic",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "predictMyMultiSigExtendedAddress",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "creationCodeStores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployMyMultiSigExtended",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployMyMultiSigExtendedDeterministic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictMyMultiSigExtendedAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MyMultiSigExtendedDeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MyMultiSigExtendedDeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    creationCodeStores(
      overrides?: CallOverrides
    ): Promise<[string, string] & { store0: string; store1: string }>;

    deployMyMultiSigExtended(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployMyMultiSigExtendedDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    predictMyMultiSigExtendedAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string] & { contractAddress: string }>;
  };

  creationCodeStores(
    overrides?: CallOverrides
  ): Promise<[string, string] & { store0: string; store1: string }>;

  deployMyMultiSigExtended(
    contractName_: PromiseOrValue<string>,
    owners_: PromiseOrValue<string>[],
    threshold_: PromiseOrValue<BigNumberish>,
    isOnlyOwnerRequest_: PromiseOrValue<boolean>,
    entryPoint_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployMyMultiSigExtendedDeterministic(
    salt_: PromiseOrValue<BytesLike>,
    contractName_: PromiseOrValue<string>,
    owners_: PromiseOrValue<string>[],
    threshold_: PromiseOrValue<BigNumberish>,
    isOnlyOwnerRequest_: PromiseOrValue<boolean>,
    entryPoint_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  predictMyMultiSigExtendedAddress(
    salt_: PromiseOrValue<BytesLike>,
    contractName_: PromiseOrValue<string>,
    owners_: PromiseOrValue<string>[],
    threshold_: PromiseOrValue<BigNumberish>,
    isOnlyOwnerRequest_: PromiseOrValue<boolean>,
    entryPoint_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    creationCodeStores(
      overrides?: CallOverrides
    ): Promise<[string, string] & { store0: string; store1: string }>;

    deployMyMultiSigExtended(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployMyMultiSigExtendedDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    predictMyMultiSigExtendedAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    creationCodeStores(overrides?: CallOverrides): Promise<BigNumber>;

    deployMyMultiSigExtended(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployMyMultiSigExtendedDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    predictMyMultiSigExtendedAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    creationCodeStores(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deployMyMultiSigExtended(
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployMyMultiSigExtendedDeterministic(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    predictMyMultiSigExtendedAddress(
      salt_: PromiseOrValue<BytesLike>,
      contractName_: PromiseOrValue<string>,
      owners_: PromiseOrValue<string>[],
      threshold_: PromiseOrValue<BigNumberish>,
      isOnlyOwnerRequest_: PromiseOrValue<boolean>,
      entryPoint_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
