/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace MyMultiSigV2_5FactorableModels {
  export type Create2ParamsStruct = {
    saltKind: PromiseOrValue<BigNumberish>;
    chainAgnosticKey: PromiseOrValue<BytesLike>;
    contractName: PromiseOrValue<string>;
    owners: PromiseOrValue<string>[];
    threshold: PromiseOrValue<BigNumberish>;
  };

  export type Create2ParamsStructOutput = [
    number,
    string,
    string,
    string[],
    number
  ] & {
    saltKind: number;
    chainAgnosticKey: string;
    contractName: string;
    owners: string[];
    threshold: number;
  };
}

export interface MyMultiSigFactorableV2_5Interface extends utils.Interface {
  functions: {
    "computeSalt((uint8,bytes32,string,address[],uint16))": FunctionFragment;
    "createMyMultiSigV2_5((uint8,bytes32,string,address[],uint16),address)": FunctionFragment;
    "isV2_5Wallet(address)": FunctionFragment;
    "myMultiSigV2_5Deployer()": FunctionFragment;
    "myMultiSigV2_5Impl()": FunctionFragment;
    "predictWalletAddress((uint8,bytes32,string,address[],uint16))": FunctionFragment;
    "v2_5Count()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "computeSalt"
      | "createMyMultiSigV2_5"
      | "isV2_5Wallet"
      | "myMultiSigV2_5Deployer"
      | "myMultiSigV2_5Impl"
      | "predictWalletAddress"
      | "v2_5Count"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "computeSalt",
    values: [MyMultiSigV2_5FactorableModels.Create2ParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createMyMultiSigV2_5",
    values: [
      MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isV2_5Wallet",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "myMultiSigV2_5Deployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "myMultiSigV2_5Impl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "predictWalletAddress",
    values: [MyMultiSigV2_5FactorableModels.Create2ParamsStruct]
  ): string;
  encodeFunctionData(functionFragment: "v2_5Count", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "computeSalt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMyMultiSigV2_5",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isV2_5Wallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "myMultiSigV2_5Deployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "myMultiSigV2_5Impl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "predictWalletAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "v2_5Count", data: BytesLike): Result;

  events: {
    "MyMultiSigV2_5Created(address,address,bytes32,string,address[],uint16)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MyMultiSigV2_5Created"): EventFragment;
}

export interface MyMultiSigV2_5CreatedEventObject {
  creator: string;
  contractAddress: string;
  salt: string;
  contractName: string;
  originalOwners: string[];
  threshold: number;
}
export type MyMultiSigV2_5CreatedEvent = TypedEvent<
  [string, string, string, string, string[], number],
  MyMultiSigV2_5CreatedEventObject
>;

export type MyMultiSigV2_5CreatedEventFilter =
  TypedEventFilter<MyMultiSigV2_5CreatedEvent>;

export interface MyMultiSigFactorableV2_5 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MyMultiSigFactorableV2_5Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    computeSalt(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    createMyMultiSigV2_5(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      entryPoint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isV2_5Wallet(
      wallet: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    myMultiSigV2_5Deployer(overrides?: CallOverrides): Promise<[string]>;

    myMultiSigV2_5Impl(overrides?: CallOverrides): Promise<[string]>;

    predictWalletAddress(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<[string, string] & { wallet: string; impl: string }>;

    v2_5Count(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  computeSalt(
    params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  createMyMultiSigV2_5(
    params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
    entryPoint: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isV2_5Wallet(
    wallet: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  myMultiSigV2_5Deployer(overrides?: CallOverrides): Promise<string>;

  myMultiSigV2_5Impl(overrides?: CallOverrides): Promise<string>;

  predictWalletAddress(
    params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
    overrides?: CallOverrides
  ): Promise<[string, string] & { wallet: string; impl: string }>;

  v2_5Count(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    computeSalt(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    createMyMultiSigV2_5(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      entryPoint: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    isV2_5Wallet(
      wallet: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    myMultiSigV2_5Deployer(overrides?: CallOverrides): Promise<string>;

    myMultiSigV2_5Impl(overrides?: CallOverrides): Promise<string>;

    predictWalletAddress(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<[string, string] & { wallet: string; impl: string }>;

    v2_5Count(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "MyMultiSigV2_5Created(address,address,bytes32,string,address[],uint16)"(
      creator?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      salt?: null,
      contractName?: null,
      originalOwners?: null,
      threshold?: null
    ): MyMultiSigV2_5CreatedEventFilter;
    MyMultiSigV2_5Created(
      creator?: PromiseOrValue<string> | null,
      contractAddress?: PromiseOrValue<string> | null,
      salt?: null,
      contractName?: null,
      originalOwners?: null,
      threshold?: null
    ): MyMultiSigV2_5CreatedEventFilter;
  };

  estimateGas: {
    computeSalt(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createMyMultiSigV2_5(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      entryPoint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isV2_5Wallet(
      wallet: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    myMultiSigV2_5Deployer(overrides?: CallOverrides): Promise<BigNumber>;

    myMultiSigV2_5Impl(overrides?: CallOverrides): Promise<BigNumber>;

    predictWalletAddress(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    v2_5Count(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    computeSalt(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createMyMultiSigV2_5(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      entryPoint: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isV2_5Wallet(
      wallet: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    myMultiSigV2_5Deployer(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    myMultiSigV2_5Impl(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    predictWalletAddress(
      params: MyMultiSigV2_5FactorableModels.Create2ParamsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    v2_5Count(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
