/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MyMultiSigDeployerInterface extends Interface {
    getFunction(nameOrSignature: "deployMyMultiSig" | "deployMyMultiSigDeterministic" | "predictMyMultiSigAddress"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'deployMyMultiSig', values: [string, AddressLike[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'deployMyMultiSigDeterministic', values: [BytesLike, string, AddressLike[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'predictMyMultiSigAddress', values: [BytesLike, string, AddressLike[], BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'deployMyMultiSig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployMyMultiSigDeterministic', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictMyMultiSigAddress', data: BytesLike): Result;
  }

  

  export interface MyMultiSigDeployer extends BaseContract {
    
    connect(runner?: ContractRunner | null): MyMultiSigDeployer;
    waitForDeployment(): Promise<this>;

    interface: MyMultiSigDeployerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    deployMyMultiSig: TypedContractMethod<
      [contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    deployMyMultiSigDeterministic: TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    predictMyMultiSigAddress: TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'deployMyMultiSig'): TypedContractMethod<
      [contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deployMyMultiSigDeterministic'): TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'predictMyMultiSigAddress'): TypedContractMethod<
      [salt_: BytesLike, contractName_: string, owners_: AddressLike[], threshold_: BigNumberish, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }