name: Hardhat Build & Test

on:
  schedule:
    # Runs "at 7h30 am every day" (see https://crontab.guru)
    - cron: '30 7 * * *'
  push:
  workflow_dispatch:

jobs:
  hardhat_build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Yarn Install
        run: yarn
      - name: Hardhat Compile
        run: yarn hardhat compile
      - name: Hardhat Test
        run: yarn hardhat test
      - name: Hardhat Coverage
        run: yarn coverage
